### ISSUE TITLE
Account Creation Workflow Modifications

### ISSUE THREAD

**Issue by piyapongch** [ualbertalib/dataverse#10]
- [ ] Investigate the workflow and options
- [ ] Option 1: Implementing Dataverse 3.6 account workflow modification
User requests a new account using Google form. The Google form will send email to Dataverse admin. The admin receives the email and creates an account using sign up form with auto-generated password and send notification email with temporary password to the user.
  - [ ] Add term of service on the create account form
  - [ ] Replace Sign Up link with create account Google Docs from when user is not logged in
  - [ ] Use Dataverse Sign Up form link when user logged in as admin
  - [ ] Prevent user to create account from Sign Up form 
  - [ ] Allow only admin user to use Sign Up form to create an account
  - [ ] Sign up form generates a temporary password and send an email to user
- [ ] Option 2: Using Dataverse 4.5 sign up process
  - [ ] Add Google reCAPTCHA to Sign Up form to prevent robot and spam
  - [ ] Remove automatically log in after Sign Up success
  - [ ] Add Sign Up email verification
