### ISSUE TITLE
User Interface Customizations

### ISSUE THREAD

**Issue by piyapongch** [ualbertalib/dataverse#15]
- [ ] Add root Dataverse logo, name and wordings
- [ ] Review and modify all wordings
- [ ] Update Dataverse term of services (https://drive.google.com/a/ualberta.ca/file/d/0B86QgxUJ28ueel93eDF0dzJ1QTQ/view?usp=sharing_)
- [ ] Replace copyright footer with UAL copyright message
