### ISSUE TITLE
Email Templates Customizations

### ISSUE THREAD

**Issue by piyapongch** [ualbertalib/dataverse#18]
- [x] Gather all email notification template for review and modification (https://docs.google.com/a/ualberta.ca/document/d/1NBma4UvjipbZxLWcPnbeMi7DDmGwmI4BgvdJL8mP_KU/edit?usp=sharing)
- [x] Modify email template wordings in source codes and/or bundle.properties
- [ ] Create email content for all email templates and confirm with stakeholders
