### ISSUE TITLE
Data Migration

### ISSUE THREAD

**Issue by piyapongch** [ualbertalib/dataverse#24]
- [x] Setup migration environment
- [x] Run 15 steps test migration scripts
- [ ] Verify metadata and data
- [ ] Production data migration plan
