### ISSUE TITLE
Tracking OAI issues

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/dataverse#63]
This issue is to track some glitches observed in the oai server under 4.9.1, after our recent upgrade. None of these are worth putting effort into fixing now; but if a harvester has a problem with them we can look into them. I've confirmed that they are all present on Harvard's Dataverse, so they aren't local bugs.

- [ ] The one that potentially affects harvesters is the requirement to specify ```set=all``` in ListRecords or ListIdentifiers (or else you get an empty list). This is a [known bug](https://github.com/IQSS/dataverse/issues/4659) but seems to be low priority upstream. We won't try to fix it unless a harvester can't cope.

In Identify response:

- [ ] the adminEmail field doesn't validate: it should contain just the email address. Currently it looks like this:

```
<adminEmail>UAL Dataverse &lt;data@ualberta.ca></adminEmail>
```

- [ ] repository name has "Dataverse" twice: ```UAL Dataverse Dataverse OAI Archive```

In [ListSets](https://dataverse.library.ualberta.ca/oai?verb=ListSets) response (and elsewhere):

- [ ] XML validation fails because ```xoai.xsd``` is no longer available at http://www.lyncode.com/xsd/xoai.xsd . This seems to be a [DSpace artefact](https://github.com/DSpace/xoai/blob/master/schemas/xoai.xsd), and DSpace instances still link to it and therefore fail XML validation. If some harvester has a problem, we'll host it ourselves.

- [ ] And of course there's the fact that we're serving over https, like many other oai servers. Will fix only in response to a problem.

**Comment by pdurbin** [comment]
The adminEmail bug is being tracked at https://github.com/IQSS/dataverse/issues/3619

**Comment by pbinkley** [comment]
@pdurbin Thanks!

**Comment by piyapongch** [comment]
This issue has been closed on the upstream repository.
